plugins {
    id 'com.android.application'
}

android {
    namespace 'bg.svetli.arcvolume'
    compileSdk 35

    defaultConfig {
        applicationId 'bg.svetli.arcvolume'
        minSdk 26
        targetSdk 28
        versionCode 5
        versionName '5.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
