plugins {
    id 'com.android.application'
}

android {
    namespace 'bg.svetli.arcvolume'
    compileSdk 35

    defaultConfig {
        applicationId 'bg.svetli.arcvolume'
        minSdk 26
        targetSdk 33
        versionCode 20
        versionName '20.0'
    }

    signingConfigs {
        debug {
            if (System.getenv('ARC_VOLUME_KEYSTORE')) {
                storeFile file(System.getenv('ARC_VOLUME_KEYSTORE'))
                storePassword 'android'
                keyAlias 'androiddebugkey'
                keyPassword 'android'
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
